import dynamic from "next/dynamic";
import Head from "next/head";

const DynamicInspector = dynamic(() =>
  import("../components/Inspector").then((mod) => mod.Inspector)
);

export default function Home() {
  return (
    <>
      <Head>
        <title>UIInspect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-red-500">
        <DynamicInspector />
      </main>
    </>
  );
}
