import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";

const DynamicInspector = dynamic(
  () =>
    import("../components/inspector/Inspector").then((mod) => mod.Inspector),
  {
    ssr: false,
  }
);

export default function Inspect() {
  const router = useRouter();
  console.log(router.query);

  const fileID = router.query.file as string;

  return (
    <>
      <Head>
        <title>UIMix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DynamicInspector fileID={fileID} />
      </main>
    </>
  );
}
